### ISSUE TITLE
code snippet missing 

### ISSUE THREAD

**Issue by kgrowkgrow** [learn-co-curriculum/ruby-oo-self-basics#1]
The section in the middle of the readme, right after this line: "The call to #showing_self should output:" there's nothing there. I think someone forgot to paste the code

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Please note, however, that if you are working in Canvas, the update may not appear right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
