### ISSUE TITLE
Code-along doesn't seem complete

### ISSUE THREAD

**Issue by inee-ader** [learn-co-curriculum/ruby-oo-self-basics#2]
Copy and paste the following code into IRB:

class Dog
  def showing_self
    puts self
  end
end 
Now that we have our Dog class ready to go, copy and paste the following method invocations into IRB:

fido = Dog.new
fido.showing_self 

The call to #showing_self should output:

# 

This does not seem to be working at all. I pasted this very thing into IRB and followed along and it did not output "#" it gave me "nil"
Consider revising.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Please note, however, that if you are working in Canvas, the update may not appear right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
